name: youthbuk
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^0.13.6
  dio: ^5.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  image_picker: ^1.0.4
  photo_manager: ^3.0.0   # ✅ iOS 저장 지원
  flutter_dotenv: ^5.1.0
  webview_flutter: ^4.13.0
  geolocator: ^9.0.2


  google_maps_flutter: ^2.2.2   
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7

  country_picker: ^2.0.17
  url_launcher: ^6.1.7
  intl: ^0.17.0

  # 반응형
  flutter_screenutil: ^5.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/3d/
    - assets/images/banner/
    - .env
